### ISSUE TITLE
BlackHole 16ch keeps turning grey and not working

### ISSUE THREAD

**Issue by austinevenson42** [ExistentialAudio/BlackHole#447] opened 2021-08-26 07:14 UTC
Hello! So I've installed BlackHole 16ch to record the audio of my mac, and I've had it for a long time with zero issues, but all of a sudden on my new computer, also a mac, it keeps disappearing, or I guess greying out. Basically I'll download it, it'll work perfectly, then by the time I need it again in a week's time it's gone. I've reinstalled the program, and that works perfectly, everything is back in order, and then it's gone again by the next time I need it. Any ideas? Thanks!

<img width="395" alt="Screen Shot 2021-08-26 at 3 11 56 AM" src="https://user-images.githubusercontent.com/89571925/130918165-971f807d-b29a-406b-b072-3c0bcea9b8c2.png">

**Comment by cityoftech** [comment] 2021-08-31 20:30
I'm starting to notice that greyout too with Blackhole 2ch on both the M1 and intel macbook pros running Big Sur 11.5.2
It happens intermittently and the cause is unknown.
Sometimes restarting your mac helps resolve the issue without needing to reinstall blackhole.
Otherwise, just reinstall blackhole.

**Comment by devinroth** [comment] 2021-08-31 21:15
Please keep an eye out to see if you notice anything that might be causing that. Hard to fix if I can’t replicate it.

You can also check the system logs for BlackHole to see if there is any unusual errors.

Devin

**Comment by mtvickery1** [comment] 2022-04-14 21:36
Hi all, 

I have also experienced this issue on my M1 Mac. Any ideas of a fix for this? It will grey out randomly and I will need to restart my computer for it to show up again.

Thanks!

**Comment by BaronAWC95014** [comment] 2022-05-28 23:04
restarting your computer seems to bring it back. but i don't want to have to always restart my computer to screen record, and i don't know what else i can do to fix it.

**Comment by orchetect** [comment] 2022-06-10 08:21
Long shot in the dark but if the driver is actually being removed, I wonder if it's a macOS gatekeeper/codesign issue and it's quarantining the driver somehow.

**Comment by devinroth** [comment] 2022-06-10 21:17
v0.4.0 is released. Reopen if you still have issues.  I believe this is fixed. I had someone who had these issue run some tests with v0.3.0 and it seemed to fix it.

**Closed by devinroth** 2022-06-10 21:17 UTC

**Comment by mdehghani65** [comment] 2022-11-12 10:43
still having this issue using BlackHole2ch.v0.4.0

I'm running Mac Air M1 Monterey 12.1

**Comment by devinroth** [comment] 2022-11-12 18:50
Is it still in HAL? Send a photo of HAL.

Devin

**Comment by mdehghani65** [comment] 2022-11-13 09:52
> Is it still in HAL? Send a photo of HAL. Devin
> […](#)

I waited until the situation reproduce then replied. yes apparently it's there
<img width="906" alt="Screen Shot 2022-11-13 at 13 11 33" src="https://user-images.githubusercontent.com/28774905/201515943-333641e7-d6a6-436d-990a-dd923bdc3da1.png">

**Comment by mdehghani65** [comment] 2022-11-13 09:56
but grayed out in midi settings
<img width="714" alt="Screen Shot 2022-11-13 at 13 24 06" src="https://user-images.githubusercontent.com/28774905/201516083-c3ecee1b-28b8-4234-8347-b794bedad21a.png">

**Comment by devinroth** [comment] 2022-11-13 15:12
Odd. And after you restart your computer?

Devin

**Comment by mdehghani65** [comment] 2022-11-13 17:42
> Odd. And after you restart your computer? Devin
> […](#)

it came back

**Comment by mdehghani65** [comment] 2023-01-10 04:21
Just wanted to say since I upgraded macOS to ventura (13.1), Blackhole stopped vanishing. 72 hours and still present.
