### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by stupidfeverishness** [ExistentialAudio/BlackHole#119] opened 2020-04-27 11:46 UTC
Hi,

I have downloaded the pkg and followed all the directions. I have restarted my Mac and it still does not install even though it says successful. I have checked the Library and the Hal folder is not there, in fact nothing installs at all. I am using High Sierra.

My issue is similar to these: https://www.reddit.com/r/audioengineering/comments/db6ibz/i_created_an_open_source_macos_virtual_audio/f22tihi?utm_source=share&utm_medium=web2x

**Comment by devinroth** [comment] 2020-04-27 14:07
Send me a photo of audio midi setup, and the HAL folder.

**Comment by stupidfeverishness** [comment] 2020-04-27 20:09
I do not have the Hal folder or any folder because nothing installs. My audio midi setup is simply my own macs microphone because blackhole does not install.

**Comment by devinroth** [comment] 2020-04-27 20:30
You do have a HAL folder. You are most likely looking in the wrong place. Your mac would not work without it. `Finder`-> `Go to Folder`  and type in `/Library/Audio/Plug-Ins/HAL/`. 

And please humor me and send me a photo of Audio Midi Setup.

**Comment by stupidfeverishness** [comment] 2020-04-27 21:04
As I said yesterday and today. NOTHING INSTALLS! My issue s similar to those I saw on reddit. This is the exact folder, I have no reason to lie, I want this to work!

![No Hal Folder 1](https://user-images.githubusercontent.com/64406155/80420643-01544b80-88d3-11ea-99bf-4c61277802da.jpeg)

![Audio Midi Devices](https://user-images.githubusercontent.com/64406155/80420666-09ac8680-88d3-11ea-89c2-21b4873d52ab.jpeg)

**Comment by devinroth** [comment] 2020-04-27 21:32
There are two different Audio folders. You are looking in the User folder and not the system one. 

Here's the USER one.  Like the one you showed me.  `/Library/Audio/`
<img width="882" alt="Screen Shot 2020-04-27 at 2 29 42 PM" src="https://user-images.githubusercontent.com/13010961/80422773-a51e0700-8893-11ea-8843-29eaf40cd4f7.png">


Here's the SYSTEM one. `~/Library/Audio/`
<img width="1055" alt="Screen Shot 2020-04-27 at 2 30 23 PM" src="https://user-images.githubusercontent.com/13010961/80422779-a7806100-8893-11ea-8ccc-22e70fe90f0f.png">

The HAL folder is required for macOS to function properly. It's not created during installation.

**Comment by stupidfeverishness** [comment] 2020-04-27 21:32
I just tried to install other programs to see if it was my Mac, something called ishowu audio installed right away, so I don't know why it's installing that but not Blackhole. Don't really know what to do. Tried installing Blackhole driver immediately after ishowu but it still isn't installing.

![ishowu audio](https://user-images.githubusercontent.com/64406155/80422960-ff8c8700-88d6-11ea-8455-e2a93318e753.jpeg)

**Comment by stupidfeverishness** [comment] 2020-04-27 21:33
That was not my user folder!!!

**Comment by stupidfeverishness** [comment] 2020-04-27 21:33
It's ok thanks, I will just use ishowu audio. Thanks for your help.

**Comment by devinroth** [comment] 2020-04-27 21:36
I think short of me physically going over there and looking at your computer I don't think I can help you.

**Comment by stupidfeverishness** [comment] 2020-04-27 21:39
It's ok, thanks for your help though, I did go to the library using 'go' and not my user library last night as all those tips were already offered. I literally did everything, as did my boyfriend on his Mac also (we are apart right now due to quarantine, hence setting this up so we connect with stuff). The only thing is we both installed High Sierra 2 days ago. We have both followed everything and tried to install but nothing happens. 

Thanks anyway though and I do appreciate your time during these crazy times.

Stay safe,

**Comment by devinroth** [comment] 2020-04-27 21:42
Here’s the thing. I would like to figure it out since if you’re having problem other people might be.

Maybe try creating a HAL folder in that location and run the installer again.

**Comment by stupidfeverishness** [comment] 2020-04-27 21:43
ok, will give that a try

**Comment by stupidfeverishness** [comment] 2020-04-27 22:11
sorry for the delay. Its still not working. Do you think our Macs are blocking the installation somehow?

**Comment by devinroth** [comment] 2020-04-27 23:52
[BlackHole.driver.zip](https://github.com/ExistentialAudio/BlackHole/files/4542572/BlackHole.driver.zip)

Try manually installing by copying BlackHole.driver to HAL and restarting your computer.

**Comment by Ryan-N** [comment] 2020-04-28 18:58
@devinroth first and foremost, BlackHole is a lifesafer -- I rely on it almost every day. Thanks a ton for making it.  

One of my classmates is also running into install issues presently.  She happens to be +7 hours and we have a call pending to get this up and running at her end.  At present, I don't know what OS she's running (only that it's Mac -- I presume Catalina).  If a traditional install, as defined by your Wiki, does NOT work, I'm grateful for this .driver workaround you explain in this thread.  

If we have to use this workaround for whatever the reason, I have a dumb and generic question to ask: when the zip file with the .driver contents ends up in her downloads folder, can she simply double-click on the .zip file while it's in the downloads folder, so as to produce its contents as a new expandable (blue icon) folder -- then move this (.driver) folder into the HAL folder you explain above?

I don't know code, and if we weren't both up against the wall on deadlines right now, I'd try un-installing BlackHole and re-installing so as to reproduce whatever all the hullabaloo is about.

After our call, if I identify something to be genuinely awry (i.e. caused by a recent OSX update), I'll circle back here to let you know.  Cheers

**Comment by stupidfeverishness** [comment] 2020-04-28 20:51
Thanks Devin, will try that

**Comment by devinroth** [comment] 2020-04-28 21:47
@Ryan-N try creating a HAL folder in the plug-ins folder and moving the .driver there. Make sure you restart the computer.

**Comment by devinroth** [comment] 2020-04-28 21:47
The plug-ins folder is created by the system. Other apps use it too.

**Comment by devinroth** [comment] 2020-04-30 17:18
@stupidfeverishness any luck?

**Comment by devinroth** [comment] 2020-05-16 17:14
@stupidfeverishness @Ryan-N did it work at all? If so I’ll update the installer.

**Comment by stupidfeverishness** [comment] 2020-05-16 17:28
Hi Devin,

Sorry for not replying sooner, we just got frustrated with trying to get anything to work that we gave up. It seems impossible to stream any game with the PS4 and Macs! I will give it another go and see what happens.

**Comment by devinroth** [comment] 2020-05-16 17:30
It's a tough one for me to figure out since I'm unable to reproduce the problem on my machine. Any help you can give would be great.

**Comment by stupidfeverishness** [comment] 2020-05-16 17:33
Ok, give me a day or so and we will give it another try and get right back to you

**Comment by FrancoRivera** [comment] 2020-07-30 15:25
HI @devinroth,

First of all huge thanks for the software, its truly amazing.

We are having a very similar issue, on Mac running Catalina with a custom BlackHole Xcode build:
1. installed the .driver under the System Library folder: `/Library/Audio/Plug-ins/HAL` 
2. Execute the command provided on the README
3. Restart the computer (as it didn't show up)
4. Deleted the driver and repeat steps 1-4

The build that we download from the website works perfectly.

We have used the [wiki](https://github.com/ExistentialAudio/BlackHole/wiki/Running-Multiple-BlackHole-Drivers) in order to run multiple devices, and it **works perfectly on other Macs** except this one. 

Would you have any insights on this behaviour?

Franco

**Comment by devinroth** [comment] 2020-07-30 15:53
If you can figure this out it would be awesome. I have no issues on my Catalina installation so it’s really hard for me to debug. 

I have two ideas that you can try. 

1. There are multiple HAL locations that you can try installing. system/Library, /Library, and ~/Library. See if any of those work. 

2. Someone mentioned something about the driver getting flagged as malware on a Catalina install. Maybe check if that’s causing a problem. 

Try looking into those ideas and let me know the results. 

Devin

**Comment by devinroth** [comment] 2020-08-10 04:30
I have a new insight which may solve the issue. While working on some new features for BlackHole all of a sudden it would no longer "install". After spending hours trying to figure it out I narrowed it down to the bundle ID. If I changed the ID from audio.existential.BlackHole to anything else including audio.existential.BlackHole1 it works. Currently I have no explanation as to why. So try changing the bundleID and see if it makes any difference.

**Comment by Ryan-N** [comment] 2020-08-10 14:13
FYI, I had to uninstall and reinstall BlackHole yesterday for the first
time.

Users who previously established a MIDI “multi-channel device” In order to
hear audio through your computer speakers, and record to BlackHole at the
same time, need to go back into that profile, click BlackHole, then click
Input and Output—wherein MUTE must be un-checked and Volume/Gain set to
something other than zero.  I am back in business.

The cause of this is unknown.  OSX update perhaps? (I allow my computer to
have software automatically updated).  What I do know, is that I tried all
sorts of things before resorting to uninstall/reinstall.  if this happens
again, I will try to change filename as per suggested here.

Ryan

**Comment by devinroth** [comment] 2020-12-08 21:40
Give the latest installer a try.

**Comment by bdozoretz** [comment] 2020-12-29 14:42
I am seeing this after upgrading to Catalina:
[BlackholeDriver.pdf](https://github.com/ExistentialAudio/BlackHole/files/5751069/BlackholeDriver.pdf)

**Comment by devinroth** [comment] 2021-01-04 08:33
This should be fixed in 0.2.8. Let me know if you run into issues.

**Closed by devinroth** 2021-01-04 08:33 UTC
Labels: bug

**Comment by HarrisonMiller101** [comment] 2021-02-03 21:06
I know this is a closed issue, but I have been trying to install this today and having the same issue. I read through the comments and did what was suggested. Perhaps I am missing something. I have tried installing both the 2 and the 16 channel, both say that they were installed successfully, but neither show up in the Audio Midi. I went to the folder in HAL and renamed it by adding a 1 to the end (not sure if that is what you meant) and still nothing. I am not sure what to do.

**Comment by devinroth** [comment] 2021-02-03 21:10
What OS are you on?

Have you restarted your computer?

Devin

**Comment by HarrisonMiller101** [comment] 2021-02-03 21:14
macOS Big Sur. And yes, I did.

**Comment by devinroth** [comment] 2021-02-03 21:16
Apple Silicon?

Devin

**Comment by devinroth** [comment] 2021-02-03 21:16
Did you update to 11.2?

Devin
