### ISSUE TITLE
problem with higher value for LATENCY_FRAME_SIZE

### ISSUE THREAD

**Issue by elpeh** [ExistentialAudio/BlackHole#286] opened 2021-02-02 09:24 UTC
Hello, thanks for this work.

I try to use BlackHole to also get a delay of around 1s in the input path. Setting LATENCY_FRAME_SIZE to 2048 does work (at least it's audio is passed and subjectively delay seems to be added, too) - but set to 48000 it does not: no audio is passed (tested with VLC and GarageBand).
As LATENCY_FRAME_SIZE is used in RING_BUFFER_FRAME_SIZE calculation, at the moment I don't see the problem.

DEBUG being defined I still only get
Feb  2 12:04:31 host coreaudiod[2861]: BlackHole_GetDevicePropertyData: could not get the plug-in bundle for kAudioDevicePropertyIcon
Feb  2 12:04:55 host coreaudiod[2861]: BlackHole-DELAY Start IO
Feb  2 12:07:28 host coreaudiod[2861]: BlackHole-DELAY Stop IO

(the icon problem also not fixed but independent of the audio behaviour)

**Comment by devinroth** [comment] 2021-02-02 18:32
I know exactly what the issue is. When reworking the whole thing for 0.2.7 I forgot to add the latency in. The driver should be reporting it correctly but I don't believe anything is delayed which of course causes issues. So then the buffer is cleared before the audio leaves hence thee silence.  I'll work on it. Should be a relatively easy fix.

Yeah I also noticed that the icons are gone with this latest version.

**Comment by devinroth** [comment] 2021-02-02 18:32
And are you sure the stream is actually delayed? It should only be reporting that it is but I don't think it actually is.

**Comment by devinroth** [comment] 2021-02-02 18:32
No need to test that. I know what the answer is.

**Comment by elpeh** [comment] 2021-02-02 21:35
Ok, thanks for the quick response. I had not found anything in the code that would look like the delay functionality. And no, as I wrote "subjectively" (the test case had been difficult to evaluate with small amount - and I in kind of a hurry having had planned to use the delay function tonight...). Awaiting the fix. Thanks!

**Comment by devinroth** [comment] 2021-02-02 21:56
Well it should be working fine in 0.2.7. 

Here's the best way to test. I use Logic Pro. I have a metronome audio click that I route out and back in using BlackHole. I record the audio file and compare the two. If they are lined up exactly then everything is working normally.

**Comment by elpeh** [comment] 2021-02-03 06:39
I'm a bit confused: "When reworking the whole thing for 0.2.7 I forgot to add the latency in.", "Well it should be working fine in 0.2.7"...should I retest with 0.2.7 or earlier? 

Another question: I don't know much about the macOS frameworks.. would it be possible to make the delay adjustable (in the easiest case on driver initialization) by e.g. a property?

**Comment by devinroth** [comment] 2021-02-03 06:41
Sorry for 0.2.8 I reworked stuff. 0.2.7 still correctly has the latency in.

**Comment by devinroth** [comment] 2021-02-03 06:43
Yes. You could adjust latency on initialization and in theory you can adjust it on the fly. In practice, many audio apps don't handle changes to audio driver well.

**Comment by orchetect** [comment] 2022-06-10 07:10
Has this been resolved in 0.3.0?

**Comment by devinroth** [comment] 2022-06-10 21:12
This is fixed. v0.4.0. Let me know if you run into any issues.

**Closed by devinroth** 2022-06-10 21:12 UTC
Labels: bug
