### ISSUE TITLE
CoreAudio error: 21646576

### ISSUE THREAD

**Issue by wgotten** [ExistentialAudio/BlackHole#179] opened 2020-07-01 19:55 UTC
Greetings - 

Running Mac 10.15.5, BlackHole 0.2.6, Waveform 11.0.39, Sibelius 2020.6, Jamulus 3.5.8.

Primary use case is routing Sibelius sound, microphone, MIDI keyboard through Waveform via BlackHole into Jamulus for collaboration, then back to Waveform for recording. I am able to successfully get what I need out of this setup.

Problem is that every so often, something hiccups - sometimes as often as every few minutes. This causes Jamulus to lock up and Waveform to forget its input and output devices (set up as aggregate devices via BlackHole). To remedy, I must restart Jamulus completely, reselect aggregate devices in Waveform, then re-input the sources in my Waveform edit file. 

There are no errors generated (that I can see). No pop-up messages. It just happens - I only know because the sound stops and the Waveform input devices disappear. And I can't narrow down what the cause is, although I think it is either BlackHole or Waveform. There doesn't seem to be any particular trigger. Does anybody have an idea what causes this or how I can track down the problem?  

Waveform logs show:

1 Jul 2020 15:37:55  CoreAudio: CoreAudio error: 21646576
1 Jul 2020 15:37:56  CoreAudio: CoreAudio error: 21646576
1 Jul 2020 15:37:56  CoreAudio: CoreAudio error: 216f626a

**Comment by devinroth** [comment] 2020-07-01 20:10
Is there anything that shows up in the system logs related to BlackHole? The next question is does this happen with BlackHole without the multi-output? I know you won’t hear anything but it will be useful information for me to look into it.

Here are the descriptions of the errors listed below. Most likely because I’m guess CoreAudio crashes and the audioID change. Which is why you need to restart the programs because they didn’t take potential core audio crashes into account.

21646576 = !dev = kAudioHardwareBadDeviceError
216f626a = !obj = kAudioHardwareBadObjectError

    @constant       kAudioHardwareBadObjectError
                        The AudioObjectID passed to the function doesn't map to a valid AudioObject.
    @constant       kAudioHardwareBadDeviceError
                        The AudioObjectID passed to the function doesn't map to a valid AudioDevice.

**Comment by wgotten** [comment] 2020-07-01 20:50
Devin,

Thanks for writing.  Appears I had an event at 15:37:55.  Here is what I see so far:

Jul  1 15:37:00 Lamonts-iMac com.apple.xpc.launchd[1] (com.apple.mdworker.shared.01000000-0400-0000-0000-000000000000[65866]): Service exited due to SIGKILL | sent by mds[133]
Jul  1 15:37:24 Lamonts-iMac com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.backupd.65876): Failed to bootstrap path: path = /System/Library/CoreServices/backupd.bundle/Contents/Resources/backupd, error = 2: No such file or directory
Jul  1 15:37:38 Lamonts-iMac com.apple.xpc.launchd[1] (com.apple.mdworker.shared.01000000-0500-0000-0000-000000000000[65870]): Service exited due to SIGKILL | sent by mds[133]
Jul  1 15:37:50 Lamonts-iMac com.apple.xpc.launchd[1] (com.apple.mdworker.shared.08000000-0200-0000-0000-000000000000[65875]): Service exited due to SIGKILL | sent by mds[133]
Jul  1 15:37:55 Lamonts-iMac com.apple.xpc.launchd[1] (com.apple.audio.coreaudiod[16676]): Service exited due to SIGABRT
Jul  1 15:37:58 Lamonts-iMac coreaudiod[65877]: BlackHole Start IO
Jul  1 15:38:03 Lamonts-iMac com.apple.xpc.launchd[1] (com.apple.mdworker.shared.07000000-0200-0000-0000-000000000000[65868]): Service exited due to SIGKILL | sent by mds[133]
Jul  1 15:38:20 Lamonts-iMac com.apple.xpc.launchd[1] (com.apple.mdworker.shared.06000000-0700-0000-0000-000000000000[65869]): Service exited due to SIGKILL | sent by mds[133]
Jul  1 15:38:40 Lamonts-iMac com.apple.xpc.launchd[1] (com.apple.mdworker.shared.02000000-0000-0000-0000-000000000000[65886]): Service exited due to SIGKILL | sent by mds[133]
Jul  1 15:38:59 Lamonts-iMac com.apple.xpc.launchd[1] (com.apple.mdworker.shared.06000000-0000-0000-0000-000000000000[65888]): Service exited due to SIGKILL | sent by mds[133]
Jul  1 15:39:00 Lamonts-iMac com.apple.xpc.launchd[1] (com.apple.mdworker.shared.07000000-0300-0000-0000-000000000000[65889]): Service exited due to SIGKILL | sent by mds[133]

com.apple.message.domain: com.apple.crashreporter.writereport.crash
com.apple.message.signature: coreaudiod
com.apple.message.signature2: UNBUNDLED ||| 5.0 (5.0)
com.apple.message.signature3: UNKNOWN
com.apple.message.result: NO
com.apple.message.summarize: YES
SenderMachUUID: AB107272-3FBA-3363-BBB9-151AFEF0791E

Does this help?

Best
Will

**Comment by devinroth** [comment] 2020-07-01 21:25
Not enough info. Could you just search for coreaudiod and see what shows up?

**Comment by wgotten** [comment] 2020-07-01 21:27
OK.  Just had another event - 2 today.  15:37:55 and 17:23:42



Jul  1 07:56:48 Lamonts-iMac coreaudiod[16676]: BlackHole Stop IO
Jul  1 07:56:48 Lamonts-iMac coreaudiod[16676]: BlackHole Start IO
Jul  1 07:56:48 Lamonts-iMac coreaudiod[16676]: BlackHole Stop IO
Jul  1 07:56:48 Lamonts-iMac coreaudiod[16676]: BlackHole Start IO
Jul  1 12:39:53 Lamonts-iMac coreaudiod[16676]: BlackHole Stop IO
Jul  1 12:40:02 Lamonts-iMac coreaudiod[16676]: BlackHole Start IO
Jul  1 12:40:08 Lamonts-iMac coreaudiod[16676]: BlackHole Stop IO
Jul  1 12:40:18 Lamonts-iMac coreaudiod[16676]: BlackHole Start IO
Jul  1 12:40:23 Lamonts-iMac coreaudiod[16676]: BlackHole Stop IO
Jul  1 12:47:20 Lamonts-iMac coreaudiod[16676]: BlackHole Start IO
Jul  1 12:47:21 Lamonts-iMac coreaudiod[16676]: BlackHole Stop IO
Jul  1 12:47:38 Lamonts-iMac coreaudiod[16676]: BlackHole Start IO
Jul  1 12:47:55 Lamonts-iMac coreaudiod[16676]: BlackHole Stop IO
Jul  1 12:47:55 Lamonts-iMac coreaudiod[16676]: BlackHole Start IO
Jul  1 14:10:33 Lamonts-iMac coreaudiod[16676]: BlackHole Stop IO
Jul  1 14:10:41 Lamonts-iMac coreaudiod[16676]: BlackHole Start IO
Jul  1 15:37:55 Lamonts-iMac com.apple.xpc.launchd[1] (com.apple.audio.coreaudiod[16676]): Service exited due to SIGABRT
Jul  1 15:37:58 Lamonts-iMac coreaudiod[65877]: BlackHole Start IO
Jul  1 17:23:42 Lamonts-iMac coreaudiod[65877]: coreaudiod(65877,0x700008740000) malloc: Incorrect checksum for freed object 0x7fa881360630: probably modified after being freed.
Jul  1 17:23:42 Lamonts-iMac com.apple.xpc.launchd[1] (com.apple.audio.coreaudiod[65877]): Service exited due to SIGABRT
Jul  1 17:23:44 Lamonts-iMac coreaudiod[84152]: BlackHole Start IO

**Comment by devinroth** [comment] 2020-07-22 00:17
Nothing here actually point to an issue with BlackHole. 

I'm guessing the issue is with Jamulus. Have you had any luck?

**Comment by wgotten** [comment] 2020-07-22 14:57
Devin,

Thanks for writing back.

I think the problem was between BlackHole and Waveform Pro.

I had to stop using BlackHole and start with a different application to achieve the same effect … since then I have had no problems. 

Best
Will

**Comment by devinroth** [comment] 2020-07-22 16:41
Got it. When i have time i’ll play around with it and see what pops up. 

Devin

**Comment by wgotten** [comment] 2020-07-22 16:47
Good luck.  Sorry I can’t be more helpful.  I could never narrow down a causal factor (which appeared to occur at random intervals from a few minutes to a few hours), and could only correlate Waveform Pro being open at the same time as BlackHole.

Best
Will

**Comment by devinroth** [comment] 2020-12-08 21:57
I best this is solved with the 0.2.8 branch I'm working on. Wanna test it?

**Comment by wgotten** [comment] 2020-12-08 22:30
Devin,

Unfortunately I had to move on to a different solution.  I’m happy you found a solution but I’m not a good person to test it.

Best regards,
Will

**Comment by devinroth** [comment] 2021-01-04 08:33
This should be fixed on 0.2.8.

**Closed by devinroth** 2021-01-04 08:33 UTC
Labels: bug
